import Head from "next/head";
import Link from "next/link";

const AvailableRoutes = [{
  id: 0,
  projectTitle: "Payments Landing Page",
  path: "/payment-landing-page"
}]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <h1>Available Routes</h1>
      <ul>
        {AvailableRoutes.map((route) => (
          <Link key={route.id} href={route.path}>
            {route.projectTitle}
          </Link>
        ))}
      </ul>
    </div>
    </>
  );
}
